# Step 1: Build Phase
FROM node:alpine3.20 AS build-phase
RUN addgroup app && adduser -S -G app app
USER app
WORKDIR /app
COPY package*.json .
RUN npm install
ENV VITE_SERVER_API=https://api-vikiasmy.bikashneupane.com
COPY . .
RUN npm run build

# Step 2: Production
FROM nginx:mainline-alpine-perl
COPY --from=build-phase /app/dist /usr/share/nginx/html
EXPOSE 80
ENTRYPOINT [ "nginx", "-g", "daemon off;" ]